/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#943700",
        "inverse-on-surface": "#f0f0fb",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-dim": "#d9d9e5",
        "secondary": "#495c95",
        "primary-container": "#2563eb",
        "tertiary-fixed": "#ffdbcd",
        "outline": "#737686",
        "error": "#ba1a1a",
        "background": "#faf8ff",
        "on-primary-fixed": "#00174b",
        "on-secondary-fixed": "#00174b",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#ededf9",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f3fe",
        "inverse-primary": "#b4c5ff",
        "surface-tint": "#0053db",
        "outline-variant": "#c3c6d7",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#360f00",
        "on-surface-variant": "#434655",
        "on-surface": "#191b23",
        "tertiary-container": "#bc4800",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#ffb596",
        "surface": "#faf8ff",
        "secondary-container": "#acbfff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#dbe1ff",
        "on-secondary-container": "#394c84",
        "surface-bright": "#faf8ff",
        "on-primary-container": "#eeefff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-variant": "#e1e2ed",
        "surface-container-high": "#e7e7f3",
        "primary-fixed-dim": "#b4c5ff",
        "secondary-fixed-dim": "#b4c5ff",
        "primary": {
          DEFAULT: "#004ac6",
          50: "#eef2ff",
          100: "#e0e7ff",
          200: "#c7d2fe",
          300: "#a5b4fc",
          400: "#818cf8",
          500: "#6366f1",
          600: "#004ac6",
          700: "#4338ca",
          800: "#3730a3",
          900: "#312e81",
          950: "#1e1b4b",
        },
        "on-secondary-fixed-variant": "#31447b",
        "on-error": "#ffffff",
        "on-background": "#191b23",
        "inverse-surface": "#2e3039",
        "on-tertiary-container": "#ffede6",
        "surface-container-highest": "#e1e2ed",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Inter"],
        "display": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
