/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      // ── Colors from pqge2.html ──────────────────────────────────────────
      colors: {
        "on-primary-fixed-variant": "#31476b",
        "surface-tint": "#495f84",
        "inverse-primary": "#b1c7f2",
        "on-tertiary-fixed-variant": "#00458f",
        "primary-fixed-dim": "#b1c7f2",
        "primary": {
          DEFAULT: "#000000",
          50: "#eef2ff",
          100: "#e0e7ff",
          200: "#c7d2fe",
          300: "#a5b4fc",
          400: "#818cf8",
          500: "#6366f1",
          600: "#004ac6",
          700: "#4338ca",
          800: "#3730a3",
          900: "#312e81",
          950: "#1e1b4b",
        },
        "tertiary-container": "#001b3f",
        "surface-bright": "#f7f9fb",
        "on-secondary": "#ffffff",
        "on-background": "#191c1e",
        "on-primary-fixed": "#001b3d",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed": "#d7e2ff",
        "tertiary-fixed-dim": "#abc7ff",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-container": "#5284d6",
        "on-secondary-fixed-variant": "#005312",
        "primary-fixed": "#d6e3ff",
        "secondary-fixed": "#99f894",
        "secondary-fixed-dim": "#7edb7b",
        "surface-container-low": "#f2f4f6",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "secondary": "#016e1c",
        "on-secondary-container": "#0b7320",
        "surface-dim": "#d8dadc",
        "on-tertiary": "#ffffff",
        "secondary-container": "#96f591",
        "surface-container": "#eceef0",
        "outline-variant": "#c4c6cf",
        "tertiary": "#000002",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-surface": "#191c1e",
        "error": "#ba1a1a",
        "surface": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "background": "#f7f9fb",
        "on-secondary-fixed": "#002204",
        "on-primary-container": "#6f84ac",
        "inverse-surface": "#2d3133",
        "outline": "#74777f",
        "on-tertiary-fixed": "#001b3f",
        "on-surface-variant": "#44474e",
        "primary-container": "#001b3d",
      },

      // ── Border Radius from pqge2.html ───────────────────────────────────
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },

      // ── Spacing tokens from pqge2.html ──────────────────────────────────
      spacing: {
        lg: "32px",
        gutter: "24px",
        base: "4px",
        xs: "8px",
        "container-max": "1440px",
        sm: "16px",
        md: "24px",
        xl: "48px",
      },

      // ── Font Families: Manrope for headings, Inter for body/labels ──────
      fontFamily: {
        "caption": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "h1": ["Manrope", "sans-serif"],
        "h2": ["Manrope", "sans-serif"],
        "h3": ["Manrope", "sans-serif"],
        // aliases
        "headline": ["Manrope", "sans-serif"],
        "display": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },

      // ── Font Size scale from pqge2.html ─────────────────────────────────
      fontSize: {
        "caption": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "600", letterSpacing: "0.05em" }],
        "h3": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "h2": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "h1": ["32px", { lineHeight: "1.2", fontWeight: "700", letterSpacing: "-0.02em" }],
      },
    },
  },
  plugins: [],
}
